packages:
  # all packages in direct subdirs of packages/
  - 'projects/*'
  # all packages in subdirs of components/
  - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'